apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sre-challenge-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  selector:
    matchLabels:
      app: sre-challenge
